### ISSUE TITLE
Enforce Https

### ISSUE THREAD

**Issue by OpAayush** [willin/js.cool#173]
Enforce https option not enableling?

**Comment by OpAayush** [comment]
I am using a subdomain does subdomains contacted enfore https?

**Comment by willin** [comment]
no. it's  a free plan. 20$/m too expensive to me.

**Comment by willin** [comment]
besides, pro plan limits only 20 page rules (free 5, already used out).

**Comment by OpAayush** [comment]
What do you mean on second message?
Subdomains will not be enforce https?

**Comment by willin** [comment]
even paid, will not.

you can just get one domain you own.

**Comment by willin** [comment]
such as .tk, .ml (free) or you can join github education pack, get a free .me, .io

**Comment by OpAayush** [comment]
I am on GitHub edu pack...

**Comment by willin** [comment]
https://education.github.com/pack/
