### ISSUE TITLE
records for feat.js.cool

### ISSUE THREAD

**Issue by atordvairn** [willin/js.cool#203]
## the google search console verification:
```google-site-verification=m880aOvo4reUVDN_rYJ5i_FnTTZXhYjqxMEbvWtKJR0```

### improvmx records
![image](https://user-images.githubusercontent.com/97218417/207867647-47792349-0b34-453c-8c53-da571c639457.png)

**Comment by willin** [comment]
| TYPE | HOSTNAME(default: feat) | VALUE |
|:--:|:--:|:--|
| TXT| feat| google-site-verification=m880aOvo4reUVDN_rYJ5i_FnTTZXhYjqxMEbvWtKJR0 |

pls make a table for me

**Comment by atordvairn** [comment]
| TYPE | HOSTNAME | VALUE |
| ----------- | ----------- | ----------- |
|   TXT   | feat.js.cool | google-site-verification=m880aOvo4reUVDN_rYJ5i_FnTTZXhYjqxMEbvWtKJR0|

**Comment by atordvairn** [comment]
improvmx one's already the table

**Comment by willin** [comment]
1

**Comment by atordvairn** [comment]
improvmx's second one too please

**Comment by atordvairn** [comment]
its the same host but diff priority and value

**Comment by willin** [comment]
<img width="910" alt="image" src="https://user-images.githubusercontent.com/1890238/208096839-bfaabf18-bc31-41de-8355-fab6cbfa6abb.png">
?

**Comment by atordvairn** [comment]
![image](https://user-images.githubusercontent.com/97218417/208099523-90c576f9-4904-41fa-8c61-8948c03c6c0a.png)

just set these too

**Comment by atordvairn** [comment]
@willin

**Comment by willin** [comment]
text it to me thx

**Comment by atordvairn** [comment]
> text it to me thx

?

**Comment by atordvairn** [comment]
| TYPE | HOSTNAME | VALUE |
| ----------- | ----------- | ----------- |
|   TXT   | feat.js.cool. | v=spf1 include:spf.improvmx.com ~all|

**Comment by willin** [comment]
1
