### ISSUE TITLE
加入PSL

### ISSUE THREAD

**Issue by cnzc** [willin/js.cool#216]
Public Suffix List (PSL) 是公用子域名列表，域名加入后会成为主域名。
目前，Firefox高亮的域名是`js.cool`，而不是`域名.js.cool`。
如果js.cool加入了PSL，那对搜索引擎收录、DNS支持等等都是有好处的，更能支持开源发展 :D
我看到您的PR（[PR链接](https://github.com/publicsuffix/list/pull/1603) ）疑似被拒，您看能不能去再申请一下，以前`js.org`都申请成功了。如果js.cool成功进入PSL那就太好了。

**Comment by willin** [comment]
那不是我的事情了。
