### ISSUE TITLE
u.js.cool 解析失败 DNS_PROBE_FINISHED_NXDOMAIN

### ISSUE THREAD

**Issue by cf-pages** [willin/js.cool#219]
错误代码：DNS_PROBE_FINISHED_NXDOMAIN

请问能帮忙检查下原因吗？谢谢！

这个域名是用作这个开源项目的：https://github.com/xyTom/Url-Shorten-Worker/

**Comment by willin** [comment]
https://short-url.pages.dev/ not works.

**Comment by cf-pages** [comment]
> https://short-url.pages.dev/ not works.

.pages.dev这个域名被国内防火墙阻断了，所以在国内无法正常访问，这也是需要使用u.js.cool域名的原因

**Comment by willin** [comment]
你先配置好测试可用性通过了再申请。

**Comment by cf-pages** [comment]
已经修改完成，由于原作者的代码是针对Cloudflare Worker写的和Cloudflare Pages的函数环境存在兼容性问题，一开始没注意到，直接用的原作者的代码在Cloudflare Pages上进行的部署，所以出现了问题，现在已经修改好了，麻烦审核一下申请，谢谢！

补充说明：为什么要部署到Cloudflare Pages上而不是像原作者那样部署到Cloudflare Worker上，是因为Cloudflare Worker自定义域名仅支持使用已经添加到Cloudflare账户中的域名，不能直接cname
