### ISSUE TITLE
Subdomain says 404: NOT_FOUND

### ISSUE THREAD

**Issue by Ziscul** [willin/js.cool#363]
Hi, I just updated my subdomain and now it's showing this screen. The original link to the website is https://ziscul.vercel.app

Is it just because I just updated it? 

![Screenshot 2023-04-30 150150](https://user-images.githubusercontent.com/99463015/235333474-919e0f8b-9824-479a-9b6c-b48175cd56bb.png)

**Comment by willin** [comment]
<img width="738" alt="image" src="https://user-images.githubusercontent.com/1890238/235340228-748e1bcd-8886-44b3-b5b9-294c8d9c4e00.png">

**Comment by Ziscul** [comment]
My bad, I forgot about vercel domains. Thank you!
