### ISSUE TITLE
How do I edit my domain

### ISSUE THREAD

**Issue by Zepvil** [willin/js.cool#372]
My original site is ziscul.js.cool and I am trying to rename it to zepvil.js.cool. I don't know how.

**Comment by Zepvil** [comment]
Translated:


我的原始站点是 ziscul.js.cool，我正在尝试将其重命名为 zepvil.js.cool。我不知道怎么办。

**Comment by willin** [comment]
add a new one named `zepvil.js.cool

**Comment by willin** [comment]
see: https://github.com/willin/domain

**Comment by Zepvil** [comment]
@willin It doesn't work.
