### ISSUE TITLE
Invalid Configuration in Vercel - zepvil.js.cool

### ISSUE THREAD

**Issue by Zepvil** [willin/js.cool#373]
Hello, I've added a domain called zepvil.js.cool and I've waited for about one day and it still doesn't work.

您好，我添加了一个名为 zepvil.js.cool 的域名，等了大约一天，仍然不起作用。

**Comment by willin** [comment]
You should go to Vercel to raise an issue

**Comment by Zepvil** [comment]
Are you sure this is a Vercel problem? It says there isn't a record or etc. 
![image](https://github.com/willin/js.cool/assets/99463015/e378d2db-0f59-423f-9245-16ef98bf78eb)

**Comment by Zepvil** [comment]
I am quite dumb. I have set the value to a string in the content section. Can you remove these two please?
![image](https://github.com/willin/js.cool/assets/99463015/bd2fcb24-7cb9-47bb-adda-51cd49fcedb3)

**Comment by willin** [comment]
<img width="1252" alt="image" src="https://github.com/willin/js.cool/assets/1890238/e3a6f14c-7435-47bd-93be-05c960fc45eb">

**Comment by willin** [comment]
<img width="132" alt="image" src="https://github.com/willin/js.cool/assets/1890238/164ed6d3-a780-458f-9b9d-cfeacff2df2c">

u can edit proxied to false

**Comment by willin** [comment]
https://zepvil.js.cool/
