### ISSUE TITLE
“由于Cloudflare免费版功能的数量限制而无法启用强制HTTPS”的可能可行的解决方案

### ISSUE THREAD

**Issue by website-pages** [willin/js.cool#98]
*此方案由个人摸索，不保证适用于所有网站。*

目前Cloudflare免费版仅支持3个Page Rules，而本项目使用的数量已经达到3个（见  #[此处](55) ）。

Github社区中有说明表示，使用Cloudflare的DNS服务的域名无法启用Github Pages的“Enforce HTTPS”功能（见 [此处](https://github.community/t/github-pages-can-t-enforce-https-for-custom-domain/121369/2)）。

所有js.cool子域名都拥有SSL证书，但未实现强制https（而且Github Pages会默认跳转到http而不是https）。

在这里，我提供一个*可能可行*的解决方案（**不保证适用于所有网站**）。
在适当位置添加下面的代码：

```
<script>
    // 非本机预览且未使用 https 时，强制重定向到 https。
    if ((!window.location.host.startsWith("localhost")) && (window.location.protocol != "https:"))
        window.location = window.location.toString().replace(/^http:/, "https:");
</script>
```

我的网站就是通过上述代码实现的。

**希望对大家有帮助！**

备注：烦请项目作者保留此issue来尽可能帮助更多人。

**Comment by willin** [comment]
Disable Proxy with `// noCF` to avoid this.
